import { Router } from "express";
import {body, param} from "express-validator";
import { createVecino, getVecino, getVecinoById, updateVecino, deleteVecino } from "../controllers/vecinos.controller.js";


const vecinosRoutes = Router()

vecinosRoutes.get('/', getVecino)
vecinosRoutes.get('/:id',param('id').isNumeric().withMessage('El id ingresado no es válido'),getVecinoById)
vecinosRoutes.post('/'
    ,body('nombre')
    .notEmpty().withMessage('El nombre del vecino no puede estar vacio')
    ,body('apellido')
    .notEmpty().withMessage('El apellido del vecino no puede estar vacio')
    ,body('dni').isNumeric()
    .notEmpty().withMessage('El dni del vecino no puede estar vacio')
    ,body('fecha_nacimiento')
    .notEmpty().withMessage('La fecha de nacimiento del vecino no puede estar vacia')
    ,body('calle')
    .notEmpty().withMessage('La calle del vecino no puede estar vacia')
    ,body('altura').isNumeric()
    .notEmpty().withMessage('La altura del vecino no puede estar vacia')
    ,body('observacion')
    .notEmpty().withMessage('La observacion del vecino no puede estar vacia')
    ,body('fecha_carga')
    .notEmpty().withMessage('La fecha_carga del vecino no puede estar vacia')
    ,body('fecha_sistema')
    .notEmpty().withMessage('La fecha_sistema del vecino no puede estar vacia')
    ,body('estado').isNumeric()
    .notEmpty().withMessage('El estado del vecino no puede estar vacio')
    ,createVecino)
vecinosRoutes.put('/:id'
    ,param('id')
    .isNumeric().withMessage('El id ingresado no es valido')
    ,body('nombre')
    .notEmpty().withMessage('El nombre del vecino no puede estar vacio')
    ,body('apellido')
    .notEmpty().withMessage('El apellido del vecino no puede estar vacio')
    ,body('dni').isNumeric()
    .notEmpty().withMessage('El dni del vecino no puede estar vacio')
    ,body('fecha_nacimiento')
    .notEmpty().withMessage('La fecha de nacimiento del vecino no puede estar vacia')
    ,body('calle')
    .notEmpty().withMessage('La calle del vecino no puede estar vacia')
    ,body('altura').isNumeric()
    .notEmpty().withMessage('La altura del vecino no puede estar vacia')
    ,body('observacion')
    .notEmpty().withMessage('La observacion del vecino no puede estar vacia')
    ,body('fecha_carga')
    .notEmpty().withMessage('La fecha_carga del vecino no puede estar vacia')
    ,body('fecha_sistema')
    .notEmpty().withMessage('La fecha_sistema del vecino no puede estar vacia')
    ,body('estado').isNumeric()
    .notEmpty().withMessage('El estado del vecino no puede estar vacio')
    ,updateVecino)
vecinosRoutes.delete('/:id'
    ,param('id')
    .isNumeric().withMessage('El id ingresado no es valido')
    ,deleteVecino)

export default vecinosRoutes